# Generated by Django 4.2.1 on 2023-05-25 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_lane_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='kanbanboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lane',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
