# Generated by Django 4.2.1 on 2023-06-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_card_display_order_alter_kanbanboard_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
